### PR TITLE
Bugfix/delay assistant

### PR DESCRIPTION
**Pull request by ervinpiol**
## Description
delay or do not reflect on assistant table after adding

## Checklist:
- [x] All of the automated tests pass
- [x] All changes has been tested locally through Docker
- [ ] If there are database revisions, all the Docker files are updated
- [ ] If there are new dependencies, they are added to the requirements text files
- [ ] If there are new environment variables, they are added to all of the deployment methods
- [ ] If there are new APIs that don't require auth, they are added to PUBLIC_ENDPOINT_SPECS
- [ ] Author has done a final read through of the PR right before merge

### CODE REVIEW

**Review by SchadenKai — CHANGES_REQUESTED** [review]
Assistant's icon is not being displayed at some of parts of the platform such as:
- Edit Teamspace Assistant Modal
- Changing Assistant in Chat Page 
You can check the images provided as context.

Screenshot 2024-12-21 191542
Screenshot 2024-12-21 191550

**Comment by SchadenKai** [comment]
resolve the merge conflict

**Comment by SchadenKai** [comment]
The issue is still there. The Assistant Icon is still not visible on the following:
- Edit Teamspace Assistant Modal
- Changing Assistant in Chat Page
- Chat intro

This might be related to an error in the `AssistantIcon` component. Check if is it working / displaying the Assistant icon in a Docker environment.
image

**Comment by ervinpiol** [comment]
resolve

**Review by SchadenKai — APPROVED** [review]

**Pull request merged**
